module.exports = {
    r_home: '',
    r_tag: 'noticias',
    r_category: 'seccion',
    r_search: 'buscar',
    r_login: 'ingresar',
    r_social_login: 'ingresar-social',
    r_verify_email: 'verificar-correo',
    r_change_email: 'cambiar-correo',
    r_unlink_email: 'desvincular-correo',
    r_2check: 'autenticacion',
    r_register: 'registrarse',
    r_forgot_password: 'recuperar-contrasena',
    r_reset_password: 'cambiar-contrasena',
    r_create_post: 'crear-publicacion',
    r_edit_post: 'editar-publicacion',
    r_settings: 'ajustes',
    r_account: 'cuenta',
    r_logins: 'inicios-de-sesion',
    r_password: 'contrasena',
    r_newsletter: 'boletin',
    r_user: 'usuario',
    r_messages: 'mensajes',
    r_saved: 'guardado',
    r_locked: 'bloqueado',
    r_blocked_users: 'usuarios-bloqueados',
    r_sitemap: 'mapa-del-sitio',
    r_rss: 'rss',
    r_page: 'pagina',
    r_terms_of_use: 'terminos-de-uso',
    r_habeas_data: 'habeas-data',
    r_about_us: 'quienes-somos',
    r_contact: 'contactar',
    r_show_palette: 'mostrar-paleta',
    r_logout: 'salir',



    //Params
    p_return: 'regresar',
    p_provider: 'proveedor',
    p_insert: 'insertar',
    p_keyword: 'palabra-clave',
    p_date: 'fecha',
    p_category: 'categoria',
    p_author: 'autor',
    p_sort: 'orden',
    p_show_alert: 'mostrar-alerta',
    p_deleted_post: 'publicacion-eliminada',
    p_comment_id: 'c',
    p_reply_id: 'r',
    p_all: 'todo',
    p_today: 'hoy',
    p_this_week: 'esta_semana',
    p_this_month: 'este_mes',
    p_this_year: 'este_anio',
    p_newest: 'mas_nuevo',
    p_oldest: 'mas_viejo',
    p_views: 'vistas',
    p_year: 'anio',
    p_month: 'mes',
    p_day: 'dia',
    p_yesterday: 'ayer',
    p_last_week: 'la_semana_pasada',
    p_user_id: 'id-del-usuario',
    p_language: 'lenguaje'
};