<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'Hybridauth\\' => array($vendorDir . '/hybridauth/hybridauth/src'),
    'DeviceDetector\\' => array($vendorDir . '/matomo/device-detector'),
);
