<?php return array(
    'root' => array(
        'name' => 'soyvillareal/php-magazine',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'd9b4c6675777795686741d553e026bf846a31e40',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'hybridauth/hybridauth' => array(
            'pretty_version' => 'v3.8.2',
            'version' => '3.8.2.0',
            'reference' => '0d6e31482c544e5ed2bdc83bd3c033054129c482',
            'type' => 'library',
            'install_path' => __DIR__ . '/../hybridauth/hybridauth',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'matomo/device-detector' => array(
            'pretty_version' => '6.0.4',
            'version' => '6.0.4.0',
            'reference' => 'aaed4d27c7a9876756d03ae85386977db306492d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../matomo/device-detector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mustangostang/spyc' => array(
            'pretty_version' => '0.6.3',
            'version' => '0.6.3.0',
            'reference' => '4627c838b16550b666d15aeae1e5289dd5b77da0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mustangostang/spyc',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.6.5',
            'version' => '6.6.5.0',
            'reference' => '8b6386d7417526d1ea4da9edb70b8352f7543627',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'piwik/device-detector' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '6.0.4',
            ),
        ),
        'soyvillareal/php-magazine' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'd9b4c6675777795686741d553e026bf846a31e40',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
