#!/bin/bash
cd /home/admin/web/phpmagazine.soyvillareal.com/public_html/assets/includes
export INFOSERVER=$(cat info.php)
rm *
cd ..
rm -d "includes"
rm "init.php"
cd ..
rm * .htaccess
rm -rf "sources" "nodejs" "requests" "sources" "themes"