#!/bin/bash
shopt -s extglob
cd /home/admin/web/phpmagazine.soyvillareal.com/public_html/assets/includes
mv info.php ../..
rm *
cd ..
rm -d "includes"
rm "init.php"
cd ..
rm * .htaccess !("info.php")
rm -rf "sources" "nodejs" "requests" "sources" "themes"
shopt -u extglob