#!/bin/bash
cd /home/admin/web/phpmagazine.soyvillareal.com/public_html

export COMPOSER_ALLOW_SUPERUSER=1;
composer install
npm install

cd /assets/includes
echo "${INFOSERVER}" > info.php
unset INFOSERVER